### ISSUE TITLE
Meta description "jQuery: .. Write Less, Do More .." on qunitjs.com

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-wp-content#399] opened 2016-09-14 03:48 UTC
The `<meta name="description">` element from the base template (`templates/jquery/header.php`) is not overridden in any of the domains. Which means it also applies to jqueryui.com, qunitjs.com, and other domains.

**Comment by scottgonzalez** [comment] 2016-09-14 13:20
Duplicate of #261.

**Closed by scottgonzalez** 2016-09-14 13:20 UTC
